const http=require('http'),fs=require('fs'),path=require('path'),crypto=require('crypto');
const PORT=process.env.PORT||3000, rooms=new Map(), streams=new Map(), pub=path.join(__dirname,'public');
const ranks=['3','4','5','6','7','8','9','10','J','Q','K','A','2','小怪','大怪'], suits=['♠','♥','♣','♦'];
const uid=()=>crypto.randomBytes(7).toString('hex'), code=()=>crypto.randomBytes(3).toString('hex').toUpperCase();
function deck(){let a=[];for(let d=0;d<3;d++){for(const s of suits)for(const r of ranks.slice(0,13))a.push({id:uid(),r,s});a.push({id:uid(),r:'小怪',s:'★'});a.push({id:uid(),r:'大怪',s:'★'});}return a.sort(()=>Math.random()-.5)}
function order(r,trump){if(r==='大怪')return 30;if(r==='小怪')return 29;return (ranks.indexOf(r)+15-(ranks.indexOf(trump)+1))%13}
function sort(hand,trump){return hand.sort((a,b)=>order(a.r,trump)-order(b.r,trump)||a.s.localeCompare(b.s))}
function makeRoom(){let c=code();while(rooms.has(c))c=code();return {code:c,players:[],host:null,started:false,trump:'2',turn:0,table:null,passes:0,ranking:[],message:'等待六位玩家入座'} }
function player(name){return {id:uid(),name:(name||'牌友').trim().slice(0,12),hand:[],connected:true}}
function join(room,name){if(room.players.length>=6)throw Error('牌桌已满（6 人）');const p=player(name);room.players.push(p);if(!room.host)room.host=p.id;room.message=`${p.name} 入座（${room.players.length}/6）`;return p}
function combo(cards,trump){if(![1,2,3,5].includes(cards.length))return null;let rs=cards.map(x=>x.r), os=rs.map(r=>order(r,trump)), unique=[...new Set(rs)];if(cards.length===1)return {kind:1,rank:os[0],label:'单张'};if(cards.length===2&&unique.length===1)return {kind:2,rank:os[0],label:'对子'};if(cards.length===3&&unique.length===1)return {kind:3,rank:os[0],label:'三张'};if(cards.length!==5)return null;
 let counts=Object.values(rs.reduce((m,r)=>(m[r]=(m[r]||0)+1,m),{})).sort((a,b)=>b-a), flush=cards.every(c=>c.s===cards[0].s&&c.s!=='★'), normal=os.every(n=>n<29), so=[...os].sort((a,b)=>a-b), straight=normal&&new Set(so).size===5&&so[4]-so[0]===4;
 if(counts[0]===5)return {kind:50,rank:so[0],label:'五根'};if(flush&&straight)return {kind:40,rank:so[4],label:'同花顺'};if(counts[0]===4)return {kind:30,rank:order(rs.find(r=>rs.filter(x=>x===r).length===4),trump),label:'四带一'};if(counts[0]===3&&counts[1]===2)return {kind:20,rank:order(rs.find(r=>rs.filter(x=>x===r).length===3),trump),label:'葫芦'};if(flush)return {kind:10,rank:so[4],label:'同花'};if(straight)return {kind:5,rank:so[4],label:'顺子'};return null }
function canBeat(c,t){if(!t)return true;if(c.kind<=3||t.kind<=3)return c.kind===t.kind&&c.rank>t.rank;if(c.kind===5)return t.kind===5&&c.rank>t.rank;if(t.kind===5)return true;return c.kind===t.kind&&c.rank>t.rank}
function start(r){if(r.players.length!==6)throw Error('必须六位玩家才能开始');let d=deck();r.players.forEach((p,i)=>p.hand=sort(d.slice(i*27,i*27+27),r.trump));r.started=true;r.turn=0;r.table=null;r.passes=0;r.ranking=[];r.message=`${r.players[0].name} 先出牌；将牌：${r.trump}`}
function publicState(r,me){return {type:'state',code:r.code,started:r.started,host:r.host,trump:r.trump,turn:r.turn,table:r.table&&{...r.table,cards:r.table.cards.map(c=>({r:c.r,s:c.s}))},passes:r.passes,ranking:r.ranking,message:r.message,players:r.players.map((p,i)=>({id:p.id,name:p.name,seat:i,team:i%2?'蓝队':'红队',count:p.hand.length,done:r.ranking.includes(p.id)})),hand:r.players.find(p=>p.id===me)?.hand||[]}}
function push(r){for(const p of r.players){let s=streams.get(p.id);if(s)s.write(`data: ${JSON.stringify(publicState(r,p.id))}\n\n`)}}
function next(r){for(let n=1;n<=6;n++){let i=(r.turn+n)%6;if(!r.ranking.includes(r.players[i].id)){r.turn=i;return}}}
function play(r,p,ids){if(!r.started)throw Error('牌局尚未开始');if(r.players[r.turn].id!==p.id)throw Error('还没轮到你');let cards=ids.map(id=>p.hand.find(c=>c.id===id));if(cards.some(!Boolean))throw Error('选牌已失效');let c=combo(cards,r.trump);if(!c)throw Error('只可出单张、对子、三张或合法五路');if(!canBeat(c,r.table?.combo))throw Error('这手牌压不住桌面');p.hand=p.hand.filter(x=>!ids.includes(x.id));r.table={player:p.id,cards,combo:c};r.passes=0;r.message=`${p.name} 出了 ${c.label}`;if(!p.hand.length){r.ranking.push(p.id);r.message=`${p.name} 率先出完牌！`;if(r.ranking.length>=5){r.started=false;r.message='本局结束：'+r.ranking.map(id=>r.players.find(p=>p.id===id).name).join('、');return}}next(r)}
function pass(r,p){if(!r.started||r.players[r.turn].id!==p.id)throw Error('还没轮到你');if(!r.table)throw Error('首出不能过');r.passes++;r.message=`${p.name} 选择不出`;if(r.passes>=r.players.length-r.ranking.length-1){let lead=r.table.player;r.table=null;r.passes=0;r.turn=r.players.findIndex(x=>x.id===lead);r.message=`无人再压，${r.players[r.turn].name} 获得出牌权`;}else next(r)}
const type={'html':'text/html','css':'text/css','js':'application/javascript'};
function json(res,status,x){res.writeHead(status,{'Content-Type':'application/json; charset=utf-8'});res.end(JSON.stringify(x))}function body(req){return new Promise(ok=>{let s='';req.on('data',c=>s+=c);req.on('end',()=>{try{ok(JSON.parse(s||'{}'))}catch{ok({})}})})}
http.createServer(async(req,res)=>{let u=new URL(req.url,`http://${req.headers.host}`),b,r,p;try{
 if(req.method==='POST'&&u.pathname==='/api/create'){b=await body(req);r=makeRoom();p=join(r,b.name);rooms.set(r.code,r);return json(res,200,{code:r.code,id:p.id})}
 if(req.method==='POST'&&u.pathname==='/api/join'){b=await body(req);r=rooms.get((b.code||'').toUpperCase());if(!r)throw Error('找不到该房间');p=join(r,b.name);push(r);return json(res,200,{code:r.code,id:p.id})}
 if(req.method==='POST'&&u.pathname==='/api/start'){b=await body(req);r=rooms.get(b.code);p=r?.players.find(x=>x.id===b.id);if(!r||!p)throw Error('房间连接已失效');if(r.host!==p.id)throw Error('只有房主可以开始');start(r);push(r);return json(res,200,{ok:true})}
 if(req.method==='POST'&&u.pathname==='/api/play'){b=await body(req);r=rooms.get(b.code);p=r?.players.find(x=>x.id===b.id);if(!p)throw Error('连接已失效');play(r,p,b.cards||[]);push(r);return json(res,200,{ok:true})}
 if(req.method==='POST'&&u.pathname==='/api/pass'){b=await body(req);r=rooms.get(b.code);p=r?.players.find(x=>x.id===b.id);if(!p)throw Error('连接已失效');pass(r,p);push(r);return json(res,200,{ok:true})}
 if(req.method==='GET'&&u.pathname==='/api/stream'){r=rooms.get(u.searchParams.get('code'));p=r?.players.find(x=>x.id===u.searchParams.get('id'));if(!p){res.writeHead(404);return res.end()}res.writeHead(200,{'Content-Type':'text/event-stream','Cache-Control':'no-cache','Connection':'keep-alive'});streams.set(p.id,res);res.write(`data: ${JSON.stringify(publicState(r,p.id))}\n\n`);req.on('close',()=>streams.delete(p.id));return}
 let file=path.join(pub,u.pathname==='/'?'index.html':u.pathname.replace(/^\/+/,''));if(!file.startsWith(pub)||!fs.existsSync(file)){res.writeHead(404);return res.end('Not found')}res.writeHead(200,{'Content-Type':(type[path.extname(file).slice(1)]||'text/plain')+'; charset=utf-8'});fs.createReadStream(file).pipe(res)
 }catch(e){json(res,400,{error:e.message||'请求失败'})}}).listen(PORT,()=>console.log(`大怪路子：http://localhost:${PORT}`));
